import ProductForm from '../../../catalog/products/components/form/ProductForm';
import { PurchaseOrderFormModal } from './PurchaseEntryModals';
import LedgerEntryModal from './modals/LedgerEntryModal';
import OrderDetailModal from './modals/OrderDetailModal';
import PoCorrectionModal from './modals/PoCorrectionModal';
import PoPaymentModal from './modals/PoPaymentModal';
import ProcessOrderModal from './modals/ProcessOrderModal';
import PurchaseReturnModal from './modals/PurchaseReturnModal';
import ReceiveInventoryModal from './modals/ReceiveInventoryModal';

const PurchaseModals = ({
  showOrderForm,
  closeOrderForm,
  poModalRef,
  isMobile,
  poModalSize,
  handlePoModalResizeStart,
  editingOrderId,
  handleOrderSubmit,
  orderFullMode,
  setOrderFullMode,
  loadingDistributorItems,
  handleLoadDistributorItems,
  orderFormData,
  setOrderFormData,
  handleDistributorInputChange,
  distributors,
  orderProductOptions,
  products,
  findProductForItem,
  calculateOrderItem,
  getAllowedPurchaseUnitsForProduct,
  getPurchasePackStep,
  handleOrderProductInputChange,
  handleOrderProductFieldFocus,
  handleOrderItemChange,
  GST_RATE_OPTIONS,
  toNumber,
  handleOrderItemRemove,
  handleOrderItemAdd,
  handleOpenPoProductForm,
  orderTotals,
  getProductSearchOptionLabel,
  orderSubmitting,
  showPoProductForm,
  closePoProductForm,
  handlePoProductSave,
  showReceiveModal,
  selectedOrder,
  setShowReceiveModal,
  receiveSubmitting,
  handleReceiveSubmit,
  receiveData,
  setReceiveData,
  handleReceiveQtyStep,
  handleReceiveItemChange,
  formatCurrency,
  getProductUomProfile,
  resolvePurchaseUnitForProduct,
  toBaseQtyForProduct,
  showOrderDetail,
  closeOrderDetail,
  orderDetail,
  orderDetailLoading,
  orderDetailSupplier,
  orderDetailEditMode,
  orderDetailDraft,
  handleOrderDetailFieldChange,
  formatDateTime,
  formatDate,
  getPoLifecycleStatus,
  getPoPaymentStatus,
  getPoPaidAmount,
  getPoBalanceDue,
  getPoNextAction,
  orderDetailItems,
  getItemFinancials,
  getOrderDetailOriginalItem,
  hasOrderDetailItemChanged,
  getOrderDetailItemFieldChanged,
  handleOrderDetailProductInputChange,
  getProductSearchLabel,
  getOrderDetailItemOriginalLabel,
  handleOrderDetailItemChange,
  handleOrderDetailItemRemove,
  handleOrderDetailItemAdd,
  orderDetailHasComputedChanges,
  orderDetailComputedTotals,
  orderDetailIsEditable,
  orderDetailSaving,
  handleOrderDetailSave,
  openOrderDetailEditMode,
  handlePrintOrderDetail,
  showProcessModal,
  processingOrder,
  closeProcessModal,
  handleProcessSubmit,
  processSubmitting,
  processFormData,
  setProcessFormData,
  getDistributorName,
  getOrderDisplayTotal,
  showPoPaymentModal,
  paymentOrder,
  closePoPaymentModal,
  handlePoPaymentSubmit,
  poPaymentSubmitting,
  poPaymentFormData,
  setPoPaymentFormData,
  showLedgerForm,
  closeLedgerForm,
  ledgerSubmitting,
  handleLedgerSubmit,
  ledgerFormData,
  setLedgerFormData,
  showPoCorrectionForm,
  selectedCorrectionOrder,
  closePoCorrectionForm,
  poCorrectionSubmitting,
  handlePoCorrectionSubmit,
  poCorrectionFormData,
  setPoCorrectionFormData,
  poCorrectionContext,
  showReturnForm,
  closeReturnForm,
  returnSubmitting,
  handleReturnSubmit,
  returnFormData,
  setReturnFormData,
  handleReturnItemAdd,
  handleReturnItemChange,
  handleReturnItemRemove
}) => (
  <>
    <PurchaseOrderFormModal
      open={showOrderForm}
      closeOrderForm={closeOrderForm}
      poModalRef={poModalRef}
      isMobile={isMobile}
      poModalSize={poModalSize}
      handlePoModalResizeStart={handlePoModalResizeStart}
      editingOrderId={editingOrderId}
      handleOrderSubmit={handleOrderSubmit}
      orderFullMode={orderFullMode}
      setOrderFullMode={setOrderFullMode}
      loadingDistributorItems={loadingDistributorItems}
      handleLoadDistributorItems={handleLoadDistributorItems}
      orderFormData={orderFormData}
      setOrderFormData={setOrderFormData}
      handleDistributorInputChange={handleDistributorInputChange}
      distributors={distributors}
      orderProductOptions={orderProductOptions}
      products={products}
      findProductForItem={findProductForItem}
      calculateOrderItem={calculateOrderItem}
      getAllowedPurchaseUnitsForProduct={getAllowedPurchaseUnitsForProduct}
      getPurchasePackStep={getPurchasePackStep}
      handleOrderProductInputChange={handleOrderProductInputChange}
      handleOrderProductFieldFocus={handleOrderProductFieldFocus}
      handleOrderItemChange={handleOrderItemChange}
      GST_RATE_OPTIONS={GST_RATE_OPTIONS}
      toNumber={toNumber}
      handleOrderItemRemove={handleOrderItemRemove}
      handleOrderItemAdd={handleOrderItemAdd}
      handleOpenProductForm={handleOpenPoProductForm}
      orderTotals={orderTotals}
      getProductSearchOptionLabel={getProductSearchOptionLabel}
      orderSubmitting={orderSubmitting}
    />

    {showPoProductForm && (
      <ProductForm
        product={null}
        mode="quick"
        onClose={closePoProductForm}
        onSave={handlePoProductSave}
      />
    )}

    <ReceiveInventoryModal
      isMobile={isMobile}
      showReceiveModal={showReceiveModal}
      selectedOrder={selectedOrder}
      setShowReceiveModal={setShowReceiveModal}
      receiveSubmitting={receiveSubmitting}
      handleReceiveSubmit={handleReceiveSubmit}
      receiveData={receiveData}
      setReceiveData={setReceiveData}
      handleReceiveQtyStep={handleReceiveQtyStep}
      handleReceiveItemChange={handleReceiveItemChange}
      formatCurrency={formatCurrency}
      toNumber={toNumber}
    />

    <OrderDetailModal
      showOrderDetail={showOrderDetail}
      closeOrderDetail={closeOrderDetail}
      orderDetail={orderDetail}
      orderDetailLoading={orderDetailLoading}
      orderDetailSupplier={orderDetailSupplier}
      orderDetailEditMode={orderDetailEditMode}
      orderDetailDraft={orderDetailDraft}
      handleOrderDetailFieldChange={handleOrderDetailFieldChange}
      formatDateTime={formatDateTime}
      formatDate={formatDate}
      getPoLifecycleStatus={getPoLifecycleStatus}
      getPoPaymentStatus={getPoPaymentStatus}
      getPoPaidAmount={getPoPaidAmount}
      getPoBalanceDue={getPoBalanceDue}
      getPoNextAction={getPoNextAction}
      orderDetailItems={orderDetailItems}
      getItemFinancials={getItemFinancials}
      getOrderDetailOriginalItem={getOrderDetailOriginalItem}
      hasOrderDetailItemChanged={hasOrderDetailItemChanged}
      getOrderDetailItemFieldChanged={getOrderDetailItemFieldChanged}
      handleOrderDetailProductInputChange={handleOrderDetailProductInputChange}
      products={products}
      getProductSearchLabel={getProductSearchLabel}
      getOrderDetailItemOriginalLabel={getOrderDetailItemOriginalLabel}
      handleOrderDetailItemChange={handleOrderDetailItemChange}
      getPurchasePackStep={getPurchasePackStep}
      getAllowedPurchaseUnitsForProduct={getAllowedPurchaseUnitsForProduct}
      handleOrderDetailItemRemove={handleOrderDetailItemRemove}
      handleOrderDetailItemAdd={handleOrderDetailItemAdd}
      orderDetailHasComputedChanges={orderDetailHasComputedChanges}
      orderDetailComputedTotals={orderDetailComputedTotals}
      orderDetailIsEditable={orderDetailIsEditable}
      orderDetailSaving={orderDetailSaving}
      handleOrderDetailSave={handleOrderDetailSave}
      openOrderDetailEditMode={openOrderDetailEditMode}
      handlePrintOrderDetail={handlePrintOrderDetail}
      GST_RATE_OPTIONS={GST_RATE_OPTIONS}
      toNumber={toNumber}
      formatCurrency={formatCurrency}
    />

    <ProcessOrderModal
      isMobile={isMobile}
      showProcessModal={showProcessModal}
      processingOrder={processingOrder}
      closeProcessModal={closeProcessModal}
      handleProcessSubmit={handleProcessSubmit}
      processSubmitting={processSubmitting}
      processFormData={processFormData}
      setProcessFormData={setProcessFormData}
      getDistributorName={getDistributorName}
      getOrderDisplayTotal={getOrderDisplayTotal}
      formatCurrency={formatCurrency}
    />

    <PoPaymentModal
      isMobile={isMobile}
      showPoPaymentModal={showPoPaymentModal}
      paymentOrder={paymentOrder}
      closePoPaymentModal={closePoPaymentModal}
      handlePoPaymentSubmit={handlePoPaymentSubmit}
      poPaymentSubmitting={poPaymentSubmitting}
      poPaymentFormData={poPaymentFormData}
      setPoPaymentFormData={setPoPaymentFormData}
      formatCurrency={formatCurrency}
      getPoBalanceDue={getPoBalanceDue}
    />

    <LedgerEntryModal
      isMobile={isMobile}
      showLedgerForm={showLedgerForm}
      closeLedgerForm={closeLedgerForm}
      ledgerSubmitting={ledgerSubmitting}
      handleLedgerSubmit={handleLedgerSubmit}
      ledgerFormData={ledgerFormData}
      setLedgerFormData={setLedgerFormData}
      distributors={distributors}
    />

    <PoCorrectionModal
      isMobile={isMobile}
      showPoCorrectionForm={showPoCorrectionForm}
      selectedCorrectionOrder={selectedCorrectionOrder}
      closePoCorrectionForm={closePoCorrectionForm}
      poCorrectionSubmitting={poCorrectionSubmitting}
      handlePoCorrectionSubmit={handlePoCorrectionSubmit}
      poCorrectionFormData={poCorrectionFormData}
      setPoCorrectionFormData={setPoCorrectionFormData}
      poCorrectionContext={poCorrectionContext}
      formatCurrency={formatCurrency}
      getDistributorName={getDistributorName}
    />

    <PurchaseReturnModal
      isMobile={isMobile}
      showReturnForm={showReturnForm}
      closeReturnForm={closeReturnForm}
      returnSubmitting={returnSubmitting}
      handleReturnSubmit={handleReturnSubmit}
      returnFormData={returnFormData}
      setReturnFormData={setReturnFormData}
      handleReturnItemAdd={handleReturnItemAdd}
      handleReturnItemChange={handleReturnItemChange}
      handleReturnItemRemove={handleReturnItemRemove}
      distributors={distributors}
      products={products}
      findProductForItem={findProductForItem}
      getAllowedPurchaseUnitsForProduct={getAllowedPurchaseUnitsForProduct}
      resolvePurchaseUnitForProduct={resolvePurchaseUnitForProduct}
      toBaseQtyForProduct={toBaseQtyForProduct}
      toNumber={toNumber}
      getProductUomProfile={getProductUomProfile}
      formatCurrency={formatCurrency}
    />
  </>
);

export default PurchaseModals;
