import PurchaseModals from './PurchaseModals';
import {
  PurchaseDashboardSection,
  PurchaseOrdersSection,
  PurchasePaymentsSection,
  PurchaseRemindersSection,
  PurchaseReturnsSection,
  PurchaseSectionTabs,
} from './sections';

const PurchaseManagementView = ({
  loading,
  error,
  success,
  activeSubTab,
  handlePurchaseSectionChange,
  operationsSummary,
  purchaseReturns,
  operationsLoading,
  operationsCardItems,
  rollupParams,
  setRollupParams,
  openCreateOrderFormForDistributor,
  handleViewOrder,
  handleOpenPoPaymentById,
  openCreateOrderForm,
  handleOpenLedgerForm,
  handleReturnFormOpen,
  formatCurrency,
  toNumber,
  filters,
  distributors,
  handleFilterChange,
  purchaseOrders,
  isPoEditable,
  canAddPaymentToPo,
  canReceivePo,
  canClosePo,
  getPoPaymentStatus,
  handleOpenProcessModal,
  handleSendDistributorWhatsApp,
  sendingWhatsAppOrderId,
  handleReceiveClick,
  handleOpenPoPaymentModal,
  handleOpenPoCorrectionForm,
  poCorrectionSubmitting,
  handleUpdateStatus,
  handleDeleteOrder,
  getOrderDisplayTotal,
  getStatusBadgeForOrder,
  getPoPaymentBadgeForOrder,
  getPoBalanceDue,
  getPoNextAction,
  ledgerBalanceSummary,
  ledgerLoading,
  ledgerRecords,
  getLedgerRowStatusClassForEntry,
  getDistributorName,
  getLedgerTypeLabel,
  getEntryDisplayBalance,
  getLedgerBillNumber,
  showOrderForm,
  closeOrderForm,
  poModalRef,
  isMobile,
  poModalSize,
  handlePoModalResizeStart,
  editingOrderId,
  handleOrderSubmit,
  orderFullMode,
  setOrderFullMode,
  loadingDistributorItems,
  handleLoadDistributorItems,
  orderFormData,
  setOrderFormData,
  handleDistributorInputChange,
  orderProductOptions,
  products,
  findProductForItem,
  calculateOrderItem,
  getAllowedPurchaseUnitsForProduct,
  getPurchasePackStep,
  handleOrderProductInputChange,
  handleOrderProductFieldFocus,
  handleOrderItemChange,
  GST_RATE_OPTIONS,
  handleOrderItemRemove,
  handleOrderItemAdd,
  handleOpenPoProductForm,
  orderTotals,
  getProductSearchOptionLabel,
  orderSubmitting,
  showPoProductForm,
  closePoProductForm,
  handlePoProductSave,
  showReceiveModal,
  selectedOrder,
  setShowReceiveModal,
  receiveSubmitting,
  handleReceiveSubmit,
  receiveData,
  setReceiveData,
  handleReceiveQtyStep,
  handleReceiveItemChange,
  getProductUomProfile,
  resolvePurchaseUnitForProduct,
  toBaseQtyForProduct,
  showOrderDetail,
  closeOrderDetail,
  orderDetail,
  orderDetailLoading,
  orderDetailSupplier,
  orderDetailEditMode,
  orderDetailDraft,
  handleOrderDetailFieldChange,
  formatDateTime,
  formatDate,
  getPoLifecycleStatus,
  getPoPaidAmount,
  orderDetailItems,
  getItemFinancials,
  getOrderDetailOriginalItem,
  hasOrderDetailItemChanged,
  getOrderDetailItemFieldChanged,
  handleOrderDetailProductInputChange,
  getProductSearchLabel,
  getOrderDetailItemOriginalLabel,
  handleOrderDetailItemChange,
  handleOrderDetailItemRemove,
  handleOrderDetailItemAdd,
  orderDetailHasComputedChanges,
  orderDetailComputedTotals,
  orderDetailIsEditable,
  orderDetailSaving,
  handleOrderDetailSave,
  openOrderDetailEditMode,
  handlePrintOrderDetail,
  showProcessModal,
  processingOrder,
  closeProcessModal,
  handleProcessSubmit,
  processSubmitting,
  processFormData,
  setProcessFormData,
  showPoPaymentModal,
  paymentOrder,
  closePoPaymentModal,
  handlePoPaymentSubmit,
  poPaymentSubmitting,
  poPaymentFormData,
  setPoPaymentFormData,
  showLedgerForm,
  closeLedgerForm,
  ledgerSubmitting,
  handleLedgerSubmit,
  ledgerFormData,
  setLedgerFormData,
  showPoCorrectionForm,
  selectedCorrectionOrder,
  closePoCorrectionForm,
  handlePoCorrectionSubmit,
  poCorrectionFormData,
  setPoCorrectionFormData,
  poCorrectionContext,
  showReturnForm,
  closeReturnForm,
  returnSubmitting,
  handleReturnSubmit,
  returnFormData,
  setReturnFormData,
  handleReturnItemAdd,
  handleReturnItemChange,
  handleReturnItemRemove,
}) => {
  if (loading) {
    return (
      <div className="purchase-management">
        <div className="loading">Loading purchase data...</div>
      </div>
    );
  }

  return (
    <div className="purchase-management">
      {error && <div className="error-message">{error}</div>}
      {success && <div className="success-message">{success}</div>}

      <PurchaseSectionTabs
        activeTab={activeSubTab}
        onChange={handlePurchaseSectionChange}
        counts={{
          reminders: operationsSummary?.reminders?.length || 0,
          returns: purchaseReturns?.length || 0,
        }}
      />

      {activeSubTab === 'dashboard' ? (
        <PurchaseDashboardSection
          operationsLoading={operationsLoading}
          operationsCardItems={operationsCardItems}
          operationsSummary={operationsSummary}
          rollupParams={rollupParams}
          setRollupParams={setRollupParams}
          onDraftDistributor={openCreateOrderFormForDistributor}
          onOpenOrder={handleViewOrder}
          onOpenPayable={handleOpenPoPaymentById}
          onNewOrder={openCreateOrderForm}
          onOpenLedgerForm={handleOpenLedgerForm}
          onOpenReturn={handleReturnFormOpen}
          formatCurrency={formatCurrency}
          toNumber={toNumber}
        />
      ) : null}

      {activeSubTab === 'orders' ? (
        <PurchaseOrdersSection
          filters={filters}
          distributors={distributors}
          onFilterChange={handleFilterChange}
          onOpenLedgerForm={handleOpenLedgerForm}
          onOpenReturn={handleReturnFormOpen}
          onNewOrder={openCreateOrderForm}
          purchaseOrders={purchaseOrders}
          isPoEditable={isPoEditable}
          canAddPaymentToPo={canAddPaymentToPo}
          canReceivePo={canReceivePo}
          canClosePo={canClosePo}
          getPoPaymentStatus={getPoPaymentStatus}
          handleViewOrder={handleViewOrder}
          handleOpenProcessModal={handleOpenProcessModal}
          handleSendDistributorWhatsApp={handleSendDistributorWhatsApp}
          sendingWhatsAppOrderId={sendingWhatsAppOrderId}
          handleReceiveClick={handleReceiveClick}
          handleOpenPoPaymentModal={handleOpenPoPaymentModal}
          handleOpenPoCorrectionForm={handleOpenPoCorrectionForm}
          poCorrectionSubmitting={poCorrectionSubmitting}
          handleUpdateStatus={handleUpdateStatus}
          handleDeleteOrder={handleDeleteOrder}
          getOrderDisplayTotal={getOrderDisplayTotal}
          getStatusBadge={getStatusBadgeForOrder}
          getPoPaymentBadge={getPoPaymentBadgeForOrder}
          getPoBalanceDue={getPoBalanceDue}
          getPoNextAction={getPoNextAction}
          formatCurrency={formatCurrency}
        />
      ) : null}

      {activeSubTab === 'payments' ? (
        <PurchasePaymentsSection
          filters={filters}
          distributors={distributors}
          onFilterChange={handleFilterChange}
          onOpenLedgerForm={handleOpenLedgerForm}
          ledgerBalanceSummary={ledgerBalanceSummary}
          payables={operationsSummary.payables || []}
          onOpenPayable={handleOpenPoPaymentById}
          ledgerLoading={ledgerLoading}
          ledgerRecords={ledgerRecords}
          getLedgerRowStatusClass={getLedgerRowStatusClassForEntry}
          getDistributorName={getDistributorName}
          getLedgerTypeLabel={getLedgerTypeLabel}
          formatCurrency={formatCurrency}
          toNumber={toNumber}
          getEntryDisplayBalance={getEntryDisplayBalance}
          getLedgerBillNumber={getLedgerBillNumber}
        />
      ) : null}

      {activeSubTab === 'reminders' ? (
        <PurchaseRemindersSection
          operationsLoading={operationsLoading}
          operationsSummary={operationsSummary}
          onDraftDistributor={openCreateOrderFormForDistributor}
          onOpenOrder={handleViewOrder}
          formatCurrency={formatCurrency}
          toNumber={toNumber}
        />
      ) : null}

      {activeSubTab === 'returns' ? (
        <PurchaseReturnsSection
          filters={filters}
          distributors={distributors}
          onFilterChange={handleFilterChange}
          onOpenReturn={handleReturnFormOpen}
          purchaseReturns={purchaseReturns}
          formatCurrency={formatCurrency}
        />
      ) : null}

      <PurchaseModals
        showOrderForm={showOrderForm}
        closeOrderForm={closeOrderForm}
        poModalRef={poModalRef}
        isMobile={isMobile}
        poModalSize={poModalSize}
        handlePoModalResizeStart={handlePoModalResizeStart}
        editingOrderId={editingOrderId}
        handleOrderSubmit={handleOrderSubmit}
        orderFullMode={orderFullMode}
        setOrderFullMode={setOrderFullMode}
        loadingDistributorItems={loadingDistributorItems}
        handleLoadDistributorItems={handleLoadDistributorItems}
        orderFormData={orderFormData}
        setOrderFormData={setOrderFormData}
        handleDistributorInputChange={handleDistributorInputChange}
        distributors={distributors}
        orderProductOptions={orderProductOptions}
        products={products}
        findProductForItem={findProductForItem}
        calculateOrderItem={calculateOrderItem}
        getAllowedPurchaseUnitsForProduct={getAllowedPurchaseUnitsForProduct}
        getPurchasePackStep={getPurchasePackStep}
        handleOrderProductInputChange={handleOrderProductInputChange}
        handleOrderProductFieldFocus={handleOrderProductFieldFocus}
        handleOrderItemChange={handleOrderItemChange}
        GST_RATE_OPTIONS={GST_RATE_OPTIONS}
        toNumber={toNumber}
        handleOrderItemRemove={handleOrderItemRemove}
        handleOrderItemAdd={handleOrderItemAdd}
        handleOpenPoProductForm={handleOpenPoProductForm}
        orderTotals={orderTotals}
        getProductSearchOptionLabel={getProductSearchOptionLabel}
        orderSubmitting={orderSubmitting}
        showPoProductForm={showPoProductForm}
        closePoProductForm={closePoProductForm}
        handlePoProductSave={handlePoProductSave}
        showReceiveModal={showReceiveModal}
        selectedOrder={selectedOrder}
        setShowReceiveModal={setShowReceiveModal}
        receiveSubmitting={receiveSubmitting}
        handleReceiveSubmit={handleReceiveSubmit}
        receiveData={receiveData}
        setReceiveData={setReceiveData}
        handleReceiveQtyStep={handleReceiveQtyStep}
        handleReceiveItemChange={handleReceiveItemChange}
        formatCurrency={formatCurrency}
        getProductUomProfile={getProductUomProfile}
        resolvePurchaseUnitForProduct={resolvePurchaseUnitForProduct}
        toBaseQtyForProduct={toBaseQtyForProduct}
        showOrderDetail={showOrderDetail}
        closeOrderDetail={closeOrderDetail}
        orderDetail={orderDetail}
        orderDetailLoading={orderDetailLoading}
        orderDetailSupplier={orderDetailSupplier}
        orderDetailEditMode={orderDetailEditMode}
        orderDetailDraft={orderDetailDraft}
        handleOrderDetailFieldChange={handleOrderDetailFieldChange}
        formatDateTime={formatDateTime}
        formatDate={formatDate}
        getPoLifecycleStatus={getPoLifecycleStatus}
        getPoPaymentStatus={getPoPaymentStatus}
        getPoPaidAmount={getPoPaidAmount}
        getPoBalanceDue={getPoBalanceDue}
        getPoNextAction={getPoNextAction}
        orderDetailItems={orderDetailItems}
        getItemFinancials={getItemFinancials}
        getOrderDetailOriginalItem={getOrderDetailOriginalItem}
        hasOrderDetailItemChanged={hasOrderDetailItemChanged}
        getOrderDetailItemFieldChanged={getOrderDetailItemFieldChanged}
        handleOrderDetailProductInputChange={handleOrderDetailProductInputChange}
        getProductSearchLabel={getProductSearchLabel}
        getOrderDetailItemOriginalLabel={getOrderDetailItemOriginalLabel}
        handleOrderDetailItemChange={handleOrderDetailItemChange}
        handleOrderDetailItemRemove={handleOrderDetailItemRemove}
        handleOrderDetailItemAdd={handleOrderDetailItemAdd}
        orderDetailHasComputedChanges={orderDetailHasComputedChanges}
        orderDetailComputedTotals={orderDetailComputedTotals}
        orderDetailIsEditable={orderDetailIsEditable}
        orderDetailSaving={orderDetailSaving}
        handleOrderDetailSave={handleOrderDetailSave}
        openOrderDetailEditMode={openOrderDetailEditMode}
        handlePrintOrderDetail={handlePrintOrderDetail}
        showProcessModal={showProcessModal}
        processingOrder={processingOrder}
        closeProcessModal={closeProcessModal}
        handleProcessSubmit={handleProcessSubmit}
        processSubmitting={processSubmitting}
        processFormData={processFormData}
        setProcessFormData={setProcessFormData}
        getDistributorName={getDistributorName}
        getOrderDisplayTotal={getOrderDisplayTotal}
        showPoPaymentModal={showPoPaymentModal}
        paymentOrder={paymentOrder}
        closePoPaymentModal={closePoPaymentModal}
        handlePoPaymentSubmit={handlePoPaymentSubmit}
        poPaymentSubmitting={poPaymentSubmitting}
        poPaymentFormData={poPaymentFormData}
        setPoPaymentFormData={setPoPaymentFormData}
        showLedgerForm={showLedgerForm}
        closeLedgerForm={closeLedgerForm}
        ledgerSubmitting={ledgerSubmitting}
        handleLedgerSubmit={handleLedgerSubmit}
        ledgerFormData={ledgerFormData}
        setLedgerFormData={setLedgerFormData}
        showPoCorrectionForm={showPoCorrectionForm}
        selectedCorrectionOrder={selectedCorrectionOrder}
        closePoCorrectionForm={closePoCorrectionForm}
        poCorrectionSubmitting={poCorrectionSubmitting}
        handlePoCorrectionSubmit={handlePoCorrectionSubmit}
        poCorrectionFormData={poCorrectionFormData}
        setPoCorrectionFormData={setPoCorrectionFormData}
        poCorrectionContext={poCorrectionContext}
        showReturnForm={showReturnForm}
        closeReturnForm={closeReturnForm}
        returnSubmitting={returnSubmitting}
        handleReturnSubmit={handleReturnSubmit}
        returnFormData={returnFormData}
        setReturnFormData={setReturnFormData}
        handleReturnItemAdd={handleReturnItemAdd}
        handleReturnItemChange={handleReturnItemChange}
        handleReturnItemRemove={handleReturnItemRemove}
      />
    </div>
  );
};

export default PurchaseManagementView;
