import { Link } from 'react-router-dom';
import AdminShell from './AdminShell';
import AdminTabContent from './AdminTabContent';
import AdminModals from './AdminModals';

const AdminPageLayout = ({
  user,
  loading,
  notification,
  closeNotification,
  isMobileSidebarOpen,
  setIsMobileSidebarOpen,
  desktopPanelCollapsed,
  setDesktopPanelCollapsed,
  SIDEBAR_SECTIONS,
  desktopActiveGroup,
  handleDesktopGroupSelect,
  desktopCurrentSection,
  activeTab,
  handleTabChange,
  mobileSidebarSections,
  expandedGroups,
  toggleSidebarGroup,
  dashboardDensity,
  setDashboardDensity,
  isMobile,
  stats,
  pendingOrdersList,
  activeProductsCount,
  inactiveProductsCount,
  lowStockProducts,
  products,
  customerUsers,
  visitorStats,
  recentOrders,
  recentCustomers,
  selectedDateKey,
  setDailySalesDate,
  loadDailySalesBills,
  dailySalesLoading,
  dailySalesError,
  dailySalesSummary,
  selectedSalesBills,
  handleAddProduct,
  setShowExportDialog,
  importBusy,
  handleStartImport,
  handleConfirmImport,
  showProductsImportCard,
  importPreviewData,
  importFile,
  importAllowIdenticalRows,
  setImportAllowIdenticalRows,
  effectiveProductViewMode,
  setProductViewMode,
  importFileInputRef,
  handleFileSelected,
  productTableSearch,
  setProductTableSearch,
  visibleProducts,
  productTableCategoryFilter,
  setProductTableCategoryFilter,
  productCategories,
  productColumnPickerRef,
  productTableVisibleColumns,
  productTableAllColumnsSelected,
  toggleSelectAllProductTableColumns,
  isProductTableColumnVisible,
  toggleProductTableColumn,
  productTableStatusFilter,
  setProductTableStatusFilter,
  productTableLowStockOnly,
  setProductTableLowStockOnly,
  selectedVisibleProduct,
  tableEditId,
  handleTableEditSave,
  tableEditSaving,
  cancelTableEdit,
  openTableEdit,
  handleEditProduct,
  productEditLoadingId,
  handleDeleteProduct,
  handlePermanentDeleteProduct,
  productTableCalculatedMinWidth,
  toggleProductTableSort,
  getSortIndicator,
  tableEditForm,
  handleTableCellClick,
  setTableEditFieldRef,
  handleTableEditChange,
  setSelectedProductId,
  selectedProductId,
  showQuickAdd,
  setShowQuickAdd,
  quickAddForm,
  setQuickAddForm,
  resetQuickAdd,
  quickSaving,
  handleQuickAddSave,
  quickEditId,
  quickEditForm,
  setQuickEditForm,
  cancelQuickEdit,
  handleQuickEditSave,
  startQuickEdit,
  getProductImageSrc,
  getProductFallbackImage,
  getCategoryPath,
  getBrandPath,
  ordersSearchQuery,
  setOrdersSearchQuery,
  visibleOrders,
  orders,
  openApproveModal,
  handleProceedToBilling,
  proceedBillingOrderId,
  handleApplyPendingFulfillment,
  usersSearchQuery,
  setUsersSearchQuery,
  filteredUsersCount,
  handleAddUser,
  users,
  filteredUsers,
  adminUsers,
  expandedUsersMap,
  toggleUserCompactRow,
  handleCompactRowKeyToggle,
  resolveMediaUrl,
  userAvatarErrors,
  setUserAvatarErrors,
  truncateUserName,
  handleEditUser,
  handleDeleteUser,
  billingPrefill,
  setBillingPrefill,
  showProductForm,
  setShowProductForm,
  editingProduct,
  setEditingProduct,
  handleProductSave,
  showApproveModal,
  setShowApproveModal,
  modalOrder,
  modalItems,
  modalLoading,
  confirmApprove,
  showExportDialog,
  exportFormat,
  setExportFormat,
  handleExportProducts,
  showCategoryManagement,
  setShowCategoryManagement,
  editingUser,
  setEditingUser,
  setShowUserForm,
  setIsCreatingUser,
  handleUserSave,
  showUserForm,
  isCreatingUser,
  handleCreateUser,
}) => {
  if (!user || user.role !== 'admin') {
    return (
      <div className="admin-page">
        <div className="admin-container">
          <h1>Access Denied</h1>
          <p>You must be an admin to access this page.</p>
          <Link to="/login" className="admin-btn">Go to Login</Link>
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="admin-page">
        <div className="admin-content">
          <div className="admin-loading-state">
            <h2>Loading admin dashboard...</h2>
            <p>Fetching orders, products, users and summary stats.</p>
          </div>
        </div>
      </div>
    );
  }

  const mainContent = (
    <AdminTabContent
      activeTab={activeTab}
      dashboardDensity={dashboardDensity}
      setDashboardDensity={setDashboardDensity}
      isMobile={isMobile}
      stats={stats}
      pendingOrdersList={pendingOrdersList}
      activeProductsCount={activeProductsCount}
      inactiveProductsCount={inactiveProductsCount}
      lowStockProducts={lowStockProducts}
      products={products}
      customerUsers={customerUsers}
      visitorStats={visitorStats}
      recentOrders={recentOrders}
      recentCustomers={recentCustomers}
      handleTabChange={handleTabChange}
      selectedDateKey={selectedDateKey}
      setDailySalesDate={setDailySalesDate}
      loadDailySalesBills={loadDailySalesBills}
      dailySalesLoading={dailySalesLoading}
      dailySalesError={dailySalesError}
      dailySalesSummary={dailySalesSummary}
      selectedSalesBills={selectedSalesBills}
      handleAddProduct={handleAddProduct}
      setShowExportDialog={setShowExportDialog}
      importBusy={importBusy}
      handleStartImport={handleStartImport}
      handleConfirmImport={handleConfirmImport}
      showProductsImportCard={showProductsImportCard}
      importPreviewData={importPreviewData}
      importFile={importFile}
      importAllowIdenticalRows={importAllowIdenticalRows}
      setImportAllowIdenticalRows={setImportAllowIdenticalRows}
      effectiveProductViewMode={effectiveProductViewMode}
      setProductViewMode={setProductViewMode}
      importFileInputRef={importFileInputRef}
      handleFileSelected={handleFileSelected}
      productTableSearch={productTableSearch}
      setProductTableSearch={setProductTableSearch}
      visibleProducts={visibleProducts}
      productTableCategoryFilter={productTableCategoryFilter}
      setProductTableCategoryFilter={setProductTableCategoryFilter}
      productCategories={productCategories}
      productColumnPickerRef={productColumnPickerRef}
      productTableVisibleColumns={productTableVisibleColumns}
      productTableAllColumnsSelected={productTableAllColumnsSelected}
      toggleSelectAllProductTableColumns={toggleSelectAllProductTableColumns}
      isProductTableColumnVisible={isProductTableColumnVisible}
      toggleProductTableColumn={toggleProductTableColumn}
      productTableStatusFilter={productTableStatusFilter}
      setProductTableStatusFilter={setProductTableStatusFilter}
      productTableLowStockOnly={productTableLowStockOnly}
      setProductTableLowStockOnly={setProductTableLowStockOnly}
      selectedVisibleProduct={selectedVisibleProduct}
      tableEditId={tableEditId}
      handleTableEditSave={handleTableEditSave}
      tableEditSaving={tableEditSaving}
      cancelTableEdit={cancelTableEdit}
      openTableEdit={openTableEdit}
      handleEditProduct={handleEditProduct}
      productEditLoadingId={productEditLoadingId}
      handleDeleteProduct={handleDeleteProduct}
      handlePermanentDeleteProduct={handlePermanentDeleteProduct}
      productTableCalculatedMinWidth={productTableCalculatedMinWidth}
      toggleProductTableSort={toggleProductTableSort}
      getSortIndicator={getSortIndicator}
      tableEditForm={tableEditForm}
      handleTableCellClick={handleTableCellClick}
      setTableEditFieldRef={setTableEditFieldRef}
      handleTableEditChange={handleTableEditChange}
      setSelectedProductId={setSelectedProductId}
      selectedProductId={selectedProductId}
      showQuickAdd={showQuickAdd}
      setShowQuickAdd={setShowQuickAdd}
      quickAddForm={quickAddForm}
      setQuickAddForm={setQuickAddForm}
      resetQuickAdd={resetQuickAdd}
      quickSaving={quickSaving}
      handleQuickAddSave={handleQuickAddSave}
      quickEditId={quickEditId}
      quickEditForm={quickEditForm}
      setQuickEditForm={setQuickEditForm}
      cancelQuickEdit={cancelQuickEdit}
      handleQuickEditSave={handleQuickEditSave}
      startQuickEdit={startQuickEdit}
      getProductImageSrc={getProductImageSrc}
      getProductFallbackImage={getProductFallbackImage}
      getCategoryPath={getCategoryPath}
      getBrandPath={getBrandPath}
      ordersSearchQuery={ordersSearchQuery}
      setOrdersSearchQuery={setOrdersSearchQuery}
      visibleOrders={visibleOrders}
      orders={orders}
      openApproveModal={openApproveModal}
      handleProceedToBilling={handleProceedToBilling}
      proceedBillingOrderId={proceedBillingOrderId}
      handleApplyPendingFulfillment={handleApplyPendingFulfillment}
      usersSearchQuery={usersSearchQuery}
      setUsersSearchQuery={setUsersSearchQuery}
      filteredUsersCount={filteredUsersCount}
      handleAddUser={handleAddUser}
      users={users}
      filteredUsers={filteredUsers}
      adminUsers={adminUsers}
      expandedUsersMap={expandedUsersMap}
      toggleUserCompactRow={toggleUserCompactRow}
      handleCompactRowKeyToggle={handleCompactRowKeyToggle}
      resolveMediaUrl={resolveMediaUrl}
      userAvatarErrors={userAvatarErrors}
      setUserAvatarErrors={setUserAvatarErrors}
      truncateUserName={truncateUserName}
      handleEditUser={handleEditUser}
      handleDeleteUser={handleDeleteUser}
      billingPrefill={billingPrefill}
      setBillingPrefill={setBillingPrefill}
      user={user}
    />
  );
  const modals = (
    <AdminModals
      showProductForm={showProductForm}
      editingProduct={editingProduct}
      setShowProductForm={setShowProductForm}
      setEditingProduct={setEditingProduct}
      handleProductSave={handleProductSave}
      showApproveModal={showApproveModal}
      modalOrder={modalOrder}
      modalItems={modalItems}
      modalLoading={modalLoading}
      confirmApprove={confirmApprove}
      setShowApproveModal={setShowApproveModal}
      proceedBillingOrderId={proceedBillingOrderId}
      handleProceedToBilling={handleProceedToBilling}
      showExportDialog={showExportDialog}
      setShowExportDialog={setShowExportDialog}
      exportFormat={exportFormat}
      setExportFormat={setExportFormat}
      importBusy={importBusy}
      handleExportProducts={handleExportProducts}
      showCategoryManagement={showCategoryManagement}
      setShowCategoryManagement={setShowCategoryManagement}
      editingUser={editingUser}
      setEditingUser={setEditingUser}
      setShowUserForm={setShowUserForm}
      setIsCreatingUser={setIsCreatingUser}
      handleUserSave={handleUserSave}
      showUserForm={showUserForm}
      isCreatingUser={isCreatingUser}
      handleCreateUser={handleCreateUser}
    />
  );

  return (
    <AdminShell
      notification={notification}
      closeNotification={closeNotification}
      isMobileSidebarOpen={isMobileSidebarOpen}
      setIsMobileSidebarOpen={setIsMobileSidebarOpen}
      desktopPanelCollapsed={desktopPanelCollapsed}
      setDesktopPanelCollapsed={setDesktopPanelCollapsed}
      SIDEBAR_SECTIONS={SIDEBAR_SECTIONS}
      desktopActiveGroup={desktopActiveGroup}
      handleDesktopGroupSelect={handleDesktopGroupSelect}
      desktopCurrentSection={desktopCurrentSection}
      activeTab={activeTab}
      handleTabChange={handleTabChange}
      mobileSidebarSections={mobileSidebarSections}
      expandedGroups={expandedGroups}
      toggleSidebarGroup={toggleSidebarGroup}
      mainContent={mainContent}
      modals={modals}
    />
  );
};

export default AdminPageLayout;
