module.exports = {
  apps: [
    {
      name: 'barman-api',
      script: 'server/index.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: 5100,
        DB_CLIENT: 'postgres',
        DB_EXECUTION_MODE: 'postgres',
        SUPABASE_DB_URL: process.env.SUPABASE_DB_URL || '',
        PG_SSL: 'true',
        PG_SSL_REJECT_UNAUTHORIZED: 'false',
        BACKUP_DIR: 'server/backups',
        FRONTEND_ORIGIN: 'http://127.0.0.1,http://localhost,http://192.168.29.18,https://narenbarman.github.io',
      },
    },
    {
      name: 'barman-ngrok',
      script: 'ngrok',
      args: ['http', '5100', '--url', 'https://techiest-really-delicia.ngrok-free.dev'],
      cwd: __dirname,
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      watch: false,
    },
  ],
};
