import usePurchaseLookups from './usePurchaseLookups';
import usePurchaseOrderFormItems from './usePurchaseOrderFormItems';
import usePurchaseOrderItemHandlers from './usePurchaseOrderItemHandlers';
import usePurchaseReceiveHandlers from './usePurchaseReceiveHandlers';
import usePurchasePaymentHandlers from './usePurchasePaymentHandlers';
import usePurchaseStatusHandlers from './usePurchaseStatusHandlers';
import usePurchaseProcessHandlers from './usePurchaseProcessHandlers';
import usePurchaseOrderDetailHandlers from './usePurchaseOrderDetailHandlers';
import usePurchaseReturnHandlers from './usePurchaseReturnHandlers';
import usePurchaseLedgerCorrections from './usePurchaseLedgerCorrections';
import usePurchasePrintOrder from './usePurchasePrintOrder';
import usePurchasePoProductForm from './usePurchasePoProductForm';
import usePurchaseOrderFormHandlers from './usePurchaseOrderFormHandlers';

const usePurchaseManagementHandlers = ({
  distributors,
  products,
  purchaseOrders,
  orderFormData,
  setOrderFormData,
  setError,
  setSuccess,
  setLoadingDistributorItems,
  buildOrderDraftItem,
  resolveProductByInputHelper,
  getDistributorProductOptionsHelper,
  getDistributorHistoryProductsHelper,
  createEmptyOrderItem,
  activePoProductField,
  setActivePoProductField,
  setPoProductFormTarget,
  setShowPoProductForm,
  poProductFormTarget,
  setProducts,
  mergeProductsById,
  setFilters,
  setActiveSubTab,
  getDefaultOrderFormData,
  setEditingOrderId,
  setOrderFullMode,
  setOrderSubmitting,
  setShowOrderForm,
  orderSubmitLockRef,
  orderSubmitting,
  toNumber,
  calculateOrderItem,
  calculateOrderTotals,
  purchaseOrdersApi,
  user,
  editingOrderId,
  orderFormClientRequestId,
  setOrderFormClientRequestId,
  createClientRequestId,
  getPurchaseRequestErrorMessage,
  fetchOrders,
  isPoEditable,
  toDateInputValue,
  productsApi,
  getProductSearchLabel,
  resolvePurchaseUnitForProduct,
  normalizeGstRateOption,
  findProductForItem,
  fetchDistributorLedger,
  setSendingWhatsAppOrderId,
  receiveData,
  setReceiveData,
  selectedOrder,
  setSelectedOrder,
  setShowReceiveModal,
  setReceiveSubmitting,
  receiveSubmitLockRef,
  getDefaultProcessFormData,
  setProcessingOrder,
  setProcessFormData,
  setShowProcessModal,
  setProcessSubmitting,
  processSubmitLockRef,
  getTodayDate,
  getOrderDisplayTotal,
  processingOrder,
  processFormData,
  getPoBalanceDue,
  getDefaultPoPaymentFormData,
  setPoPaymentFormData,
  setPaymentOrder,
  setShowPoPaymentModal,
  setPoPaymentSubmitting,
  poPaymentSubmitting,
  poPaymentLockRef,
  poPaymentClientRequestIdRef,
  paymentOrder,
  poPaymentFormData,
  orderDetail,
  orderDetailDraft,
  setOrderDetail,
  setOrderDetailDraft,
  setShowOrderDetail,
  setOrderDetailLoading,
  setOrderDetailEditMode,
  setOrderDetailSaving,
  returnFormData,
  setReturnFormData,
  setShowReturnForm,
  setReturnSubmitting,
  returnSubmitLockRef,
  purchaseReturnsApi,
  fetchReturns,
  distributorLedgerApi,
  calculateOrderBalanceAmount,
  normalizeTextKey,
  getDefaultPoCorrectionFormData,
  getDefaultLedgerFormData,
  setShowPoCorrectionForm,
  setSelectedCorrectionOrder,
  setPoCorrectionFormData,
  setPoCorrectionContext,
  setPoCorrectionSubmitting,
  poCorrectionLockRef,
  selectedCorrectionOrder,
  poCorrectionSubmitting,
  poCorrectionFormData,
  setShowLedgerForm,
  setLedgerFormData,
  setLedgerSubmitting,
  ledgerSubmitLockRef,
  ledgerSubmitting,
  ledgerFormData,
  addLocalLedgerEntry,
  localLedgerKey,
  filters,
  getOrderDistributorInfo,
  getProductUomProfile,
  toBaseQtyForProduct,
  getPoLifecycleStatus,
  getPoPaymentStatus,
  getPoPaidAmount,
  formatDate,
  formatCurrency,
  escapeHtml,
  printHtmlDocument,}) => {
  const {
    resolveProductByInput,
    getDistributorProductOptions,
    getDistributorHistoryProducts,
    handleDistributorInputChange,
  } = usePurchaseLookups({
    distributors,
    products,
    purchaseOrders,
    buildOrderDraftItem,
    setOrderFormData,
    resolveProductByInputHelper,
    getDistributorProductOptionsHelper,
    getDistributorHistoryProductsHelper,
  });

  const {
    handleOrderItemAdd,
    handleOrderItemRemove,
    ensureOrderFormItemAtIndex,
    getTargetPoProductField,
    handleOrderProductFieldFocus,
    handleLoadDistributorItems,
  } = usePurchaseOrderFormItems({
    orderFormData,
    setOrderFormData,
    createEmptyOrderItem,
    activePoProductField,
    setActivePoProductField,
    setError,
    setSuccess,
    setLoadingDistributorItems,
    distributors,
    getDistributorHistoryProducts,
  });

  const {
    handleOpenPoProductForm,
    closePoProductForm: closePoProductFormLocal,
    handlePoProductSave,
  } = usePurchasePoProductForm({
    getTargetPoProductField,
    ensureOrderFormItemAtIndex,
    setPoProductFormTarget,
    setActivePoProductField,
    setShowPoProductForm,
    poProductFormTarget,
    setProducts,
    mergeProductsById,
    setOrderFormData,
    createEmptyOrderItem,
    buildOrderDraftItem,
    setSuccess,
  });

  const {
    handleFilterChange,
    openCreateOrderForm, openCreateOrderFormForDistributor,
    closeOrderForm, handlePurchaseSectionChange,
    handleOrderSubmit,
    handleEditOrder,
  } = usePurchaseOrderFormHandlers({
    setFilters,
    setActiveSubTab,
    closePoProductForm: closePoProductFormLocal,
    getDefaultOrderFormData,
    setOrderFormData,
    setEditingOrderId,
    setOrderFullMode,
    setOrderSubmitting,
    setLoadingDistributorItems,
    setActivePoProductField,
    setPoProductFormTarget,
    setShowOrderForm,
    orderSubmitLockRef,
    orderSubmitting,
    orderFormData,
    distributors,
    products,
    buildOrderDraftItem,
    createEmptyOrderItem,
    toNumber,
    calculateOrderItem,
    calculateOrderTotals,
    findProductForItem,
    purchaseOrdersApi,
    user,
    editingOrderId,
    orderFormClientRequestId,
    setOrderFormClientRequestId,
    createClientRequestId,
    setError,
    getPurchaseRequestErrorMessage,
    fetchOrders,
    isPoEditable,
    toDateInputValue,
  });

  const {
    handleOrderItemChange, handleOrderProductInputChange,
  } = usePurchaseOrderItemHandlers({
    orderFormData,
    setOrderFormData,
    products,
    productsApi,
    resolveProductByInput,
    getProductSearchLabel,
    resolvePurchaseUnitForProduct,
    normalizeGstRateOption,
    toNumber,
    findProductForItem,
  });

  const {
    handleUpdateStatus: handleUpdateStatusInternal,
    handleSendDistributorWhatsApp,
    handleDeleteOrder,
  } = usePurchaseStatusHandlers({
    purchaseOrdersApi,
    fetchOrders,
    fetchDistributorLedger,
    setError,
    setSuccess,
    setSendingWhatsAppOrderId,
  });

  const {
    handleReceiveClick,
    handleReceiveItemChange,
    handleReceiveQtyStep,
    handleReceiveSubmit,
  } = usePurchaseReceiveHandlers({
    receiveData,
    setReceiveData,
    selectedOrder,
    setSelectedOrder,
    setShowReceiveModal,
    setReceiveSubmitting,
    receiveSubmitLockRef,
    purchaseOrdersApi,
    user,
    fetchOrders,
    setError,
    toNumber,
  });

  const {
    handleOpenProcessModal,
    closeProcessModal,
    handleProcessSubmit,
  } = usePurchaseProcessHandlers({
    getDefaultProcessFormData,
    setProcessingOrder,
    setProcessFormData,
    setShowProcessModal,
    setProcessSubmitting,
    processSubmitLockRef,
    handleUpdateStatus: handleUpdateStatusInternal,
    getTodayDate,
    toNumber,
    getOrderDisplayTotal,
    user,
    processingOrder,
    processFormData,
    setError,
  });

  const {
    handleOpenPoPaymentModal,
    handleOpenPoPaymentById,
    closePoPaymentModal,
    handlePoPaymentSubmit,
  } = usePurchasePaymentHandlers({
    purchaseOrders,
    getPoBalanceDue,
    getDefaultPoPaymentFormData,
    setPoPaymentFormData,
    setPaymentOrder,
    setShowPoPaymentModal,
    setPoPaymentSubmitting,
    poPaymentSubmitting,
    poPaymentLockRef,
    poPaymentClientRequestIdRef,
    purchaseOrdersApi,
    createClientRequestId,
    getTodayDate,
    toNumber,
    user,
    paymentOrder,
    poPaymentFormData,
    fetchOrders,
    fetchDistributorLedger,
    setError,
  });

  const {
    closeOrderDetail, handleOrderDetailFieldChange,
    handleOrderDetailItemChange, handleOrderDetailProductInputChange,
    handleOrderDetailItemAdd, handleOrderDetailItemRemove,
    openOrderDetailEditMode,
    handleOrderDetailSave,
    handleViewOrder,
  } = usePurchaseOrderDetailHandlers({
    orderDetail,
    orderDetailDraft,
    setOrderDetail,
    setOrderDetailDraft,
    setShowOrderDetail,
    setOrderDetailLoading,
    setOrderDetailEditMode,
    setOrderDetailSaving,
    setError,
    setSuccess,
    purchaseOrdersApi,
    products,
    toDateInputValue,
    getProductSearchLabel,
    resolvePurchaseUnitForProduct,
    normalizeGstRateOption,
    toNumber,
    calculateOrderItem,
    calculateOrderTotals,
    createEmptyOrderItem,
    isPoEditable,
    resolveProductByInput,
    getPurchaseRequestErrorMessage,
    fetchOrders,
  });

  const {
    handleReturnFormOpen,
    closeReturnForm,
    handleReturnItemAdd,
    handleReturnItemChange,
    handleReturnItemRemove,
    handleReturnSubmit,
  } = usePurchaseReturnHandlers({
    returnFormData,
    setReturnFormData,
    setShowReturnForm,
    setReturnSubmitting,
    returnSubmitLockRef,
    setError,
    products,
    resolvePurchaseUnitForProduct,
    findProductForItem,
    toNumber,
    purchaseReturnsApi,
    user,
    fetchReturns,
  });

  const {
    closePoCorrectionForm,
    handleOpenPoCorrectionForm,
    handlePoCorrectionSubmit,
    handleOpenLedgerForm,
    closeLedgerForm,
    handleLedgerSubmit,
  } = usePurchaseLedgerCorrections({
    distributorLedgerApi,
    calculateOrderBalanceAmount,
    toNumber,
    normalizeTextKey,
    getDefaultPoCorrectionFormData,
    getDefaultLedgerFormData,
    setShowPoCorrectionForm,
    setSelectedCorrectionOrder,
    setPoCorrectionFormData,
    setPoCorrectionContext,
    setPoCorrectionSubmitting,
    poCorrectionLockRef,
    selectedCorrectionOrder,
    poCorrectionSubmitting,
    poCorrectionFormData,
    setError,
    fetchDistributorLedger,
    user,
    setShowLedgerForm,
    setLedgerFormData,
    setLedgerSubmitting,
    ledgerSubmitLockRef,
    ledgerSubmitting,
    ledgerFormData,
    addLocalLedgerEntry,
    localLedgerKey,
    filters,
  });

  const { handlePrintOrderDetail, getItemFinancials } = usePurchasePrintOrder({
    products,
    distributors,
    getOrderDistributorInfo,
    resolvePurchaseUnitForProduct,
    getProductUomProfile,
    toBaseQtyForProduct,
    toNumber,
    getOrderDisplayTotal,
    getPoLifecycleStatus,
    getPoPaymentStatus,
    getPoPaidAmount,
    getPoBalanceDue,
    formatDate,
    formatCurrency,
    escapeHtml,
    printHtmlDocument,
    setError,
    findProductForItem,
  });

  return {
    getDistributorProductOptions,
    handleDistributorInputChange,
    handleOrderItemAdd, handleOrderItemRemove, handleOrderProductFieldFocus,
    handleLoadDistributorItems,
    handleOpenPoProductForm,
    closePoProductForm: closePoProductFormLocal,
    handlePoProductSave,
    handleFilterChange,
    openCreateOrderForm,
    openCreateOrderFormForDistributor,
    closeOrderForm,
    handlePurchaseSectionChange,
    handleOrderSubmit,
    handleEditOrder,
    handleOrderItemChange,
    handleOrderProductInputChange,
    handleUpdateStatus: handleUpdateStatusInternal,
    handleSendDistributorWhatsApp,
    handleDeleteOrder,
    handleReceiveClick, handleReceiveItemChange, handleReceiveQtyStep, handleReceiveSubmit,
    handleOpenProcessModal,
    closeProcessModal,
    handleProcessSubmit,
    handleOpenPoPaymentModal, handleOpenPoPaymentById, closePoPaymentModal, handlePoPaymentSubmit,
    closeOrderDetail,
    handleOrderDetailFieldChange,
    handleOrderDetailItemChange,
    handleOrderDetailProductInputChange,
    handleOrderDetailItemAdd,
    handleOrderDetailItemRemove,
    openOrderDetailEditMode,
    handleOrderDetailSave,
    handleViewOrder,
    handleReturnFormOpen, closeReturnForm, handleReturnItemAdd,
    handleReturnItemChange, handleReturnItemRemove, handleReturnSubmit,
    closePoCorrectionForm,
    handleOpenPoCorrectionForm,
    handlePoCorrectionSubmit,
    handleOpenLedgerForm,
    closeLedgerForm,
    handleLedgerSubmit,
    handlePrintOrderDetail,
    getItemFinancials,
  };
};

export default usePurchaseManagementHandlers;
