import { useCallback, useEffect, useState } from 'react';
import { useNavigate, useParams, useSearchParams } from 'react-router-dom';
import { statsApi, productsApi, ordersApi, usersApi, adminApi, billingApi, resolveMediaUrl } from '../api/index.js';
import { getProductImageSrc, getProductFallbackImage } from '../../../shared/utils/productImage';
import { truncateUserName } from '../../../shared/utils/formatters';
import useLockBodyScroll from '../../../shared/hooks/useLockBodyScroll';
import useIsMobile from '../../../shared/hooks/useIsMobile';
import { MOBILE_ALLOWED_TABS, MOBILE_SIDEBAR_SECTIONS, SIDEBAR_SECTIONS } from '../config/adminSidebarConfig';
import {
  PRODUCT_TABLE_ALL_COLUMN_KEYS,
  PRODUCT_TABLE_COLUMN_MIN_WIDTH,
  PRODUCT_TABLE_DEFAULT_VISIBLE_COLUMNS,
} from '../config/productTableConfig';
import { asNumber, getBrandPath, getCategoryPath, toLocalDateKey } from '../utils/adminHelpers';
import useAdminProductHandlers from './useAdminProductHandlers';
import useAdminQuickProductActions from './useAdminQuickProductActions';
import useAdminState from './useAdminState';
import useAdminComputedData from './useAdminComputedData';
import useAdminProductTable from './useAdminProductTable';
import useAdminImportExport from './useAdminImportExport';
import useAdminDataLoaders from './useAdminDataLoaders';
import useAdminOrderActions from './useAdminOrderActions';
import useAdminUserActions from './useAdminUserActions';
import useAdminNavigation from './useAdminNavigation';
import useAdminEffects from './useAdminEffects';

const useAdminPageController = ({ user }) => {
  const navigate = useNavigate();
  const { tab: routeTab = '' } = useParams();
  const [searchParams, setSearchParams] = useSearchParams();
  const isMobile = useIsMobile();
  const {
    activeTab,
    setActiveTab,
    stats,
    setStats,
    visitorStats,
    setVisitorStats,
    products,
    setProducts,
    orders,
    setOrders,
    users,
    setUsers,
    recentOrdersPreview,
    setRecentOrdersPreview,
    recentCustomersPreview,
    setRecentCustomersPreview,
    userDirectorySummary,
    setUserDirectorySummary,
    ordersPage,
    setOrdersPage,
    ordersTotal,
    setOrdersTotal,
    ordersLoading,
    setOrdersLoading,
    usersPage,
    setUsersPage,
    usersTotal,
    setUsersTotal,
    usersLoading,
    setUsersLoading,
    bills,
    setBills,
    dailySalesDate,
    setDailySalesDate,
    dailySalesLoading,
    setDailySalesLoading,
    dailySalesError,
    setDailySalesError,
    loading,
    setLoading,
    showProductForm,
    setShowProductForm,
    editingProduct,
    setEditingProduct,
    editingUser,
    setEditingUser,
    showUserForm,
    setShowUserForm,
    isCreatingUser,
    setIsCreatingUser,
    notification,
    setNotification,
    showApproveModal,
    setShowApproveModal,
    modalOrder,
    setModalOrder,
    modalItems,
    setModalItems,
    modalLoading,
    setModalLoading,
    billingPrefill,
    setBillingPrefill,
    proceedBillingOrderId,
    setProceedBillingOrderId,
    isMobileSidebarOpen,
    setIsMobileSidebarOpen,
    userAvatarErrors,
    setUserAvatarErrors,
    ordersSearchQuery,
    setOrdersSearchQuery,
    usersSearchQuery,
    setUsersSearchQuery,
    expandedUsersMap,
    setExpandedUsersMap,
    dashboardDensity,
    setDashboardDensity,
    productViewMode,
    setProductViewMode,
    showQuickAdd,
    setShowQuickAdd,
    quickSaving,
    setQuickSaving,
    quickAddForm,
    setQuickAddForm,
    quickEditId,
    setQuickEditId,
    quickEditForm,
    setQuickEditForm,
    productTableSearch,
    setProductTableSearch,
    productTableSortField,
    setProductTableSortField,
    productTableSortDir,
    setProductTableSortDir,
    productTableCategoryFilter,
    setProductTableCategoryFilter,
    productTableStatusFilter,
    setProductTableStatusFilter,
    productTableLowStockOnly,
    setProductTableLowStockOnly,
    productTableVisibleColumns,
    setProductTableVisibleColumns,
    selectedProductId,
    setSelectedProductId,
    tableEditId,
    setTableEditId,
    tableEditFocusField,
    setTableEditFocusField,
    tableEditSaving,
    setTableEditSaving,
    productEditLoadingId,
    setProductEditLoadingId,
    tableEditForm,
    setTableEditForm,
    importFile,
    setImportFile,
    showExportDialog,
    setShowExportDialog,
    exportFormat,
    setExportFormat,
    importPreviewData,
    setImportPreviewData,
    importAllowIdenticalRows,
    setImportAllowIdenticalRows,
    importBusy,
    setImportBusy,
    importFileInputRef,
    tableEditFieldRefs,
    productColumnPickerRef,
    latestKnownOrderIdRef,
    expandedGroups,
    setExpandedGroups,
    desktopActiveGroup,
    setDesktopActiveGroup,
    desktopPanelCollapsed,
    setDesktopPanelCollapsed,
  } = useAdminState({
    toLocalDateKey,
    PRODUCT_TABLE_DEFAULT_VISIBLE_COLUMNS,
    PRODUCT_TABLE_ALL_COLUMN_KEYS,
    SIDEBAR_SECTIONS,
  });
  const [billingShortcutRequest, setBillingShortcutRequest] = useState(0);
  const [purchaseShortcutRequest, setPurchaseShortcutRequest] = useState(0);

  const showNotification = useCallback((message, type) => {
    setNotification({ message, type });
    setTimeout(() => setNotification(null), 3000);
  }, [setNotification]);

  const closeNotification = useCallback(() => {
    setNotification(null);
  }, [setNotification]);

  const {
    refreshAdminData,
    ensureTabData,
    loadOrdersPage,
    loadUsersPage,
    loadDailySalesBills,
  } = useAdminDataLoaders({
    statsApi,
    productsApi,
    ordersApi,
    usersApi,
    adminApi,
    billingApi,
    setStats,
    setProducts,
    setOrders,
    setUsers,
    setRecentOrdersPreview,
    setRecentCustomersPreview,
    setUserDirectorySummary,
    setOrdersPage,
    setOrdersTotal,
    setOrdersLoading,
    setUsersPage,
    setUsersTotal,
    setUsersLoading,
    setVisitorStats,
    setBills,
    setDailySalesLoading,
    setDailySalesError,
    setLoading,
    showNotification,
    asNumber,
  });
  const refreshOrdersData = useCallback(async () => {
    await loadOrdersPage({
      page: ordersPage,
      query: ordersSearchQuery,
      silent: false,
    });
  }, [
    loadOrdersPage,
    ordersPage,
    ordersSearchQuery,
  ]);
  const {
    desktopCurrentSection,
    mobileSidebarSections,
    toggleSidebarGroup,
    handleDesktopGroupSelect,
    handleTabChange,
  } = useAdminNavigation({
    activeTab,
    setActiveTab,
    isMobile,
    routeTab,
    navigate,
    MOBILE_ALLOWED_TABS,
    SIDEBAR_SECTIONS,
    MOBILE_SIDEBAR_SECTIONS,
    setExpandedGroups,
    desktopActiveGroup,
    setDesktopActiveGroup,
    desktopPanelCollapsed,
    setDesktopPanelCollapsed,
    setIsMobileSidebarOpen,
  });

  useLockBodyScroll(isMobileSidebarOpen);

  useEffect(() => {
    const shortcutAction = String(searchParams.get('shortcut') || '').trim().toLowerCase();
    const shortcutToken = String(searchParams.get('shortcutToken') || '').trim();
    if (!shortcutAction || !shortcutToken) return;

    const next = new URLSearchParams(searchParams);
    next.delete('shortcut');
    next.delete('shortcutToken');

    if (shortcutAction === 'billing-focus') {
      if (activeTab !== 'billing') {
        setActiveTab('billing');
      }
      setBillingShortcutRequest((current) => current + 1);
    } else if (shortcutAction === 'open-po') {
      if (activeTab !== 'purchases') {
        setActiveTab('purchases');
      }
      setPurchaseShortcutRequest((current) => current + 1);
    }

    setSearchParams(next, { replace: true });
  }, [activeTab, searchParams, setActiveTab, setSearchParams]);

  useAdminEffects({
    user,
    navigate,
    ensureTabData,
    setLoading,
    orders,
    activeTab,
    ordersPage,
    ordersSearchQuery,
    loadOrdersPage,
    usersPage,
    setUsersPage,
    usersSearchQuery,
    loadUsersPage,
    latestKnownOrderIdRef,
    showNotification,
    loadDailySalesBills,
    dailySalesDate,
    productColumnPickerRef,
    tableEditId,
    tableEditFocusField,
    tableEditFieldRefs,
    productViewMode,
    dashboardDensity,
    productTableVisibleColumns,
    desktopActiveGroup,
    desktopPanelCollapsed,
  });

  const toggleUserCompactRow = (userId) => {
    setExpandedUsersMap((prev) => ({ ...prev, [userId]: !prev[userId] }));
  };

  const handleCompactRowKeyToggle = (event, userId) => {
    if (event.key === 'Enter' || event.key === ' ') {
      event.preventDefault();
      toggleUserCompactRow(userId);
    }
  };

  const {
    handleDeleteProduct,
    handlePermanentDeleteProduct,
    handleEditProduct,
    handleAddProduct,
    handleProductSave,
  } = useAdminProductHandlers({
    productsApi,
    statsApi,
    setProducts,
    setStats,
    showNotification,
    setEditingProduct,
    setShowProductForm,
    setProductEditLoadingId,
    editingProduct,
  });
  const {
    resetQuickAdd,
    handleQuickAddSave,
    startQuickEdit,
    cancelQuickEdit,
    handleQuickEditSave,
  } = useAdminQuickProductActions({
    quickAddForm,
    quickEditForm,
    setQuickAddForm,
    setQuickEditForm,
    setQuickEditId,
    setShowQuickAdd,
    setQuickSaving,
    productsApi,
    handleProductSave,
    showNotification,
    getBrandPath,
    getCategoryPath,
  });

  const {
    handleDeleteUser,
    handleEditUser,
    handleUserSave,
    handleAddUser,
    handleCreateUser,
  } = useAdminUserActions({
    currentUser: user,
    usersApi,
    setUsers,
    loadUsersPage,
    usersPage,
    usersSearchQuery,
    setUsersSearchQuery,
    showNotification,
    setEditingUser,
    setIsCreatingUser,
    setShowUserForm,
  });

  const {
    productCategories,
    activeProductsCount,
    inactiveProductsCount,
    customerUsers,
    adminUsers,
    filteredUsers,
    filteredUsersCount,
    visibleOrders,
    recentOrders,
    lowStockProducts,
    recentCustomers,
    selectedDateKey,
    selectedSalesBills,
    dailySalesSummary,
  } = useAdminComputedData({
    products,
    users,
    orders,
    recentOrdersPreview,
    recentCustomersPreview,
    bills,
    dailySalesDate,
    toLocalDateKey,
    asNumber,
    getCategoryPath,
  });

  const {
    visibleProducts,
    productTableAllColumnsSelected,
    isProductTableColumnVisible,
    toggleProductTableColumn,
    toggleSelectAllProductTableColumns,
    productTableCalculatedMinWidth,
    selectedVisibleProduct,
    toggleProductTableSort,
    getSortIndicator,
    setTableEditFieldRef,
    openTableEdit,
    handleTableCellClick,
    cancelTableEdit,
    handleTableEditChange,
    handleTableEditSave,
  } = useAdminProductTable({
    products,
    productTableSearch,
    productTableCategoryFilter,
    productTableStatusFilter,
    productTableLowStockOnly,
    productTableSortField,
    productTableSortDir,
    productTableVisibleColumns,
    PRODUCT_TABLE_ALL_COLUMN_KEYS,
    PRODUCT_TABLE_DEFAULT_VISIBLE_COLUMNS,
    PRODUCT_TABLE_COLUMN_MIN_WIDTH,
    setProductTableVisibleColumns,
    setProductTableSortField,
    setProductTableSortDir,
    selectedProductId,
    setSelectedProductId,
    tableEditId,
    setTableEditId,
    setTableEditFocusField,
    setTableEditForm,
    setTableEditSaving,
    tableEditForm,
    productsApi,
    handleProductSave,
    showNotification,
    getCategoryPath,
    getBrandPath,
    asNumber,
    setQuickEditId,
    tableEditFieldRefs,
  });

  const {
    handleExportProducts,
    handleStartImport,
    handleFileSelected,
    handleConfirmImport,
  } = useAdminImportExport({
    productsApi,
    user,
    importFile,
    setImportFile,
    importPreviewData,
    setImportPreviewData,
    importAllowIdenticalRows,
    setImportAllowIdenticalRows,
    setImportBusy,
    importBusy,
    importFileInputRef,
    showNotification,
    handleProductSave,
    setShowExportDialog,
    exportFormat,
  });
  const {
    openApproveModal,
    confirmApprove,
    handleApplyPendingFulfillment,
    handleProceedToBilling,
  } = useAdminOrderActions({
    ordersApi,
    user,
    setModalLoading,
    setModalOrder,
    setModalItems,
    setShowApproveModal,
    modalOrder,
    showNotification,
    refreshAdminData,
    refreshOrdersData,
    setProceedBillingOrderId,
    setBillingPrefill,
    handleTabChange,
  });

  const effectiveProductViewMode = isMobile ? 'grid' : productViewMode;

  const showProductsImportCard = !isMobile && Boolean(
    importPreviewData?.batch_id
    || importPreviewData?.summary
    || (Array.isArray(importPreviewData?.preview) && importPreviewData.preview.length > 0)
  );

  return {
    user,
    loading,
    notification,
    closeNotification,
    isMobileSidebarOpen,
    setIsMobileSidebarOpen,
    desktopPanelCollapsed,
    setDesktopPanelCollapsed,
    SIDEBAR_SECTIONS,
    desktopActiveGroup,
    handleDesktopGroupSelect,
    desktopCurrentSection,
    activeTab,
    handleTabChange,
    mobileSidebarSections,
    expandedGroups,
    toggleSidebarGroup,
    dashboardDensity,
    setDashboardDensity,
    isMobile,
    stats,
    billingShortcutRequest,
    setBillingShortcutRequest,
    purchaseShortcutRequest,
    setPurchaseShortcutRequest,
    activeProductsCount,
    inactiveProductsCount,
    lowStockProducts,
    products,
    visitorStats,
    userDirectorySummary,
    recentOrders,
    recentCustomers,
    selectedDateKey,
    setDailySalesDate,
    loadDailySalesBills,
    dailySalesLoading,
    dailySalesError,
    dailySalesSummary,
    selectedSalesBills,
    handleAddProduct,
    setShowExportDialog,
    importBusy,
    handleStartImport,
    handleConfirmImport,
    showProductsImportCard,
    importPreviewData,
    importFile,
    importAllowIdenticalRows,
    setImportAllowIdenticalRows,
    effectiveProductViewMode,
    setProductViewMode,
    importFileInputRef,
    handleFileSelected,
    productTableSearch,
    setProductTableSearch,
    visibleProducts,
    productTableCategoryFilter,
    setProductTableCategoryFilter,
    productCategories,
    productColumnPickerRef,
    productTableVisibleColumns,
    productTableAllColumnsSelected,
    toggleSelectAllProductTableColumns,
    isProductTableColumnVisible,
    toggleProductTableColumn,
    productTableStatusFilter,
    setProductTableStatusFilter,
    productTableLowStockOnly,
    setProductTableLowStockOnly,
    selectedVisibleProduct,
    tableEditId,
    handleTableEditSave,
    tableEditSaving,
    cancelTableEdit,
    openTableEdit,
    handleEditProduct,
    productEditLoadingId,
    handleDeleteProduct,
    handlePermanentDeleteProduct,
    productTableCalculatedMinWidth,
    toggleProductTableSort,
    getSortIndicator,
    tableEditForm,
    handleTableCellClick,
    setTableEditFieldRef,
    handleTableEditChange,
    setSelectedProductId,
    selectedProductId,
    showQuickAdd,
    setShowQuickAdd,
    quickAddForm,
    setQuickAddForm,
    resetQuickAdd,
    quickSaving,
    handleQuickAddSave,
    quickEditId,
    quickEditForm,
    setQuickEditForm,
    cancelQuickEdit,
    handleQuickEditSave,
    startQuickEdit,
    getProductImageSrc,
    getProductFallbackImage,
    getCategoryPath,
    getBrandPath,
    ordersSearchQuery,
    setOrdersSearchQuery,
    visibleOrders,
    orders,
    ordersPage,
    setOrdersPage,
    ordersTotal,
    ordersLoading,
    openApproveModal,
    handleProceedToBilling,
    proceedBillingOrderId,
    handleApplyPendingFulfillment,
    usersSearchQuery,
    setUsersSearchQuery,
    filteredUsersCount,
    handleAddUser,
    users,
    filteredUsers,
    adminUsers,
    customerUsers,
    usersPage,
    setUsersPage,
    usersTotal,
    usersLoading,
    expandedUsersMap,
    toggleUserCompactRow,
    handleCompactRowKeyToggle,
    resolveMediaUrl,
    userAvatarErrors,
    setUserAvatarErrors,
    truncateUserName,
    handleEditUser,
    handleDeleteUser,
    billingPrefill,
    setBillingPrefill,
    showProductForm,
    setShowProductForm,
    editingProduct,
    setEditingProduct,
    handleProductSave,
    showApproveModal,
    setShowApproveModal,
    modalOrder,
    modalItems,
    modalLoading,
    confirmApprove,
    showExportDialog,
    exportFormat,
    setExportFormat,
    handleExportProducts,
    editingUser,
    setEditingUser,
    setShowUserForm,
    setIsCreatingUser,
    handleUserSave,
    showUserForm,
    isCreatingUser,
    handleCreateUser,
  };
};

export default useAdminPageController;
