const createNotificationConfig = ({ env, parseBooleanEnv } = {}) => {
  const PURCHASE_OPERATIONS_NOTIFICATIONS_ENABLED = parseBooleanEnv(
    env.PURCHASE_OPERATIONS_NOTIFICATIONS_ENABLED,
    true
  );
  const PURCHASE_OPERATIONS_NOTIFICATION_INTERVAL_MS = Math.max(
    5 * 60 * 1000,
    Number(env.PURCHASE_OPERATIONS_NOTIFICATION_INTERVAL_MS || 60 * 60 * 1000)
  );
  const APP_NOTIFICATION_RETENTION_DAYS = Math.max(
    1,
    Math.min(365, Number(env.APP_NOTIFICATION_RETENTION_DAYS || 60))
  );
  const APP_NOTIFICATION_PURGE_BATCH_LIMIT = Math.max(
    1,
    Math.min(50000, Number(env.APP_NOTIFICATION_PURGE_BATCH_LIMIT || 2000))
  );
  const APP_NOTIFICATION_PURGE_INTERVAL_MS = Math.max(
    5 * 60 * 1000,
    Number(env.APP_NOTIFICATION_PURGE_INTERVAL_MS || 6 * 60 * 60 * 1000)
  );
  const CUSTOMER_REQUEST_RETENTION_DAYS = Math.max(
    1,
    Math.min(365, Number(env.CUSTOMER_REQUEST_RETENTION_DAYS || 60))
  );
  const CUSTOMER_REQUEST_PURGE_BATCH_LIMIT = Math.max(
    1,
    Math.min(50000, Number(env.CUSTOMER_REQUEST_PURGE_BATCH_LIMIT || 2000))
  );
  const CUSTOMER_REQUEST_PURGE_INTERVAL_MS = Math.max(
    5 * 60 * 1000,
    Number(env.CUSTOMER_REQUEST_PURGE_INTERVAL_MS || 6 * 60 * 60 * 1000)
  );

  return {
    PURCHASE_OPERATIONS_NOTIFICATIONS_ENABLED,
    PURCHASE_OPERATIONS_NOTIFICATION_INTERVAL_MS,
    APP_NOTIFICATION_RETENTION_DAYS,
    APP_NOTIFICATION_PURGE_BATCH_LIMIT,
    APP_NOTIFICATION_PURGE_INTERVAL_MS,
    CUSTOMER_REQUEST_RETENTION_DAYS,
    CUSTOMER_REQUEST_PURGE_BATCH_LIMIT,
    CUSTOMER_REQUEST_PURGE_INTERVAL_MS,
  };
};

module.exports = { createNotificationConfig };
