const createPhoneChangeConfig = ({ env, parseBooleanEnv } = {}) => {
  const PHONE_CHANGE_STATUS_PENDING = 'PENDING_VALIDATION';
  const PHONE_CHANGE_STATUS_APPROVED = 'APPROVED';
  const PHONE_CHANGE_STATUS_REJECTED = 'REJECTED';
  const PHONE_CHANGE_DECISION_AUTO = 'AUTO';
  const PHONE_CHANGE_DECISION_ADMIN = 'ADMIN';
  const PHONE_CHANGE_EXPIRED_REASON = 'Admin review window expired';
  const PHONE_CHANGE_CRON_SECRET = String(
    env.PHONE_CHANGE_CRON_SECRET || env.CRON_SECRET || ''
  ).trim();
  const PHONE_CHANGE_CRON_ENABLED = parseBooleanEnv(
    env.PHONE_CHANGE_CRON_ENABLED,
    Boolean(PHONE_CHANGE_CRON_SECRET)
  );
  const PHONE_CHANGE_MIN_AUTO_APPROVE_DELAY_MS = env.NODE_ENV === 'test' ? 500 : 5 * 60 * 1000;
  const PHONE_CHANGE_AUTO_APPROVE_DELAY_MS = Math.max(
    PHONE_CHANGE_MIN_AUTO_APPROVE_DELAY_MS,
    Number(env.PHONE_CHANGE_AUTO_APPROVE_DELAY_MS || 60 * 60 * 1000)
  );
  const PHONE_CHANGE_ADMIN_REVIEW_WINDOW_DAYS_RAW = Number(env.PHONE_CHANGE_ADMIN_REVIEW_WINDOW_DAYS || 5);
  const PHONE_CHANGE_ADMIN_REVIEW_WINDOW_DAYS = env.NODE_ENV === 'test'
    ? Math.max(0, PHONE_CHANGE_ADMIN_REVIEW_WINDOW_DAYS_RAW)
    : Math.max(1, Math.min(14, PHONE_CHANGE_ADMIN_REVIEW_WINDOW_DAYS_RAW));
  const PHONE_CHANGE_PROCESS_INTERVAL_MS = Math.max(
    30 * 1000,
    Number(env.PHONE_CHANGE_PROCESS_INTERVAL_MS || 60 * 1000)
  );
  const PHONE_CHANGE_AUTO_BATCH_SIZE = Math.max(
    1,
    Math.min(100, Number(env.PHONE_CHANGE_AUTO_BATCH_SIZE || 25))
  );

  return {
    PHONE_CHANGE_STATUS_PENDING,
    PHONE_CHANGE_STATUS_APPROVED,
    PHONE_CHANGE_STATUS_REJECTED,
    PHONE_CHANGE_DECISION_AUTO,
    PHONE_CHANGE_DECISION_ADMIN,
    PHONE_CHANGE_EXPIRED_REASON,
    PHONE_CHANGE_CRON_SECRET,
    PHONE_CHANGE_CRON_ENABLED,
    PHONE_CHANGE_AUTO_APPROVE_DELAY_MS,
    PHONE_CHANGE_ADMIN_REVIEW_WINDOW_DAYS,
    PHONE_CHANGE_PROCESS_INTERVAL_MS,
    PHONE_CHANGE_AUTO_BATCH_SIZE,
  };
};

module.exports = { createPhoneChangeConfig };
