const registerAuthResetModeRoutes = (deps) => {
  const {
    app,
    requireAuth,
    authIpLimiter,
    emailVerificationLimiter,
    requireInternalCron,
    dbGetAsync,
    dbRunAsync,
    dbAllAsync,
    normalizeEmail,
    parsePhoneInput,
    normalizePhone,
    hashPassword,
    generateTemporaryPassword,
    isUniqueViolationError,
    generateOtpCode,
    OTP_TTL_SECONDS,
    OTP_MAX_ATTEMPTS,
    notificationService,
    createNotificationEvent,
    EMAIL_DELIVERY_MODE,
    emailVerificationProvider,
    updateNotificationEventStatus,
    AUTH_LOGIN_OTP_EXPOSE_CODE,
    isSupabaseEmailAuthUsable,
    supabaseAuthProvider,
    syncLocalUserFromSupabaseAuth,
    getSupabaseUserMetadata,
    sanitizeUser,
    generateToken,
    toSupabaseSessionPayload,
    verifyPassword,
    isSupabaseAuthStrictMode,
    queueContactVerificationRequest,
    getRequestIp,
    syncLocalEmailVerifiedFromSupabase,
    completeContactVerificationRequests,
    EMAIL_VERIFY_MAX_ATTEMPTS,
    hashVerificationToken,
    getBearerTokenFromRequest,
    isSupabaseEmailVerified,
    EMAIL_VERIFICATION_MODE,
    SUPABASE_AUTH_MODE,
    WHATSAPP_DELIVERY_MODE,
    whatsappProvider,
    processPendingPhoneChangeRequests,
    getLatestPhoneChangeRequestForUser,
    serializePhoneChangeRequest,
    getOpenPhoneChangeRequestForUser,
    rejectPhoneChangeRequest,
    createAppNotification,
    PHONE_CHANGE_STATUS_REJECTED,
    PHONE_CHANGE_AUTO_BATCH_SIZE,
    normalizeContactVerificationRequestType,
    AUTH_FLOW_MODE,
    OTP_PROVIDER,
    OTP_DELIVERY_MODE,
    OTP_VERIFY_SESSION_TTL_SECONDS,
    PHONE_VERIFICATION_REQUIRED,
    WHATSAPP_PROVIDER,
    SUPABASE_EMAIL_VERIFY_REDIRECT,
    PHONE_VERIFY_MAX_ATTEMPTS,
    hashOpaqueToken
  } = deps;

app.get('/api/auth/reset-mode', (_, res) => {
  return res.json({
    auth_flow_mode: AUTH_FLOW_MODE,
    mode: 'otp_login_only',
    auth_methods: {
      otp: true,
      oauth: Boolean(supabaseAuthProvider?.shouldUseOAuth?.()),
      password: false,
    },
    otp_provider: OTP_PROVIDER,
    otp_delivery_mode: OTP_DELIVERY_MODE,
    otp_ready: true,
    otp_verify_session_ttl_seconds: OTP_VERIFY_SESSION_TTL_SECONDS,
    phone_verification_required: PHONE_VERIFICATION_REQUIRED,
    whatsapp_delivery_mode: WHATSAPP_DELIVERY_MODE,
    whatsapp_provider: WHATSAPP_PROVIDER,
    whatsapp_provider_ready: Boolean(whatsappProvider?.isReady),
    email_verification_mode: EMAIL_VERIFICATION_MODE,
    email_delivery_mode: EMAIL_DELIVERY_MODE,
    email_provider_ready: Boolean(emailVerificationProvider?.isReady),
    supabase_auth_enabled: Boolean(supabaseAuthProvider?.isEnabled),
    supabase_auth_mode: SUPABASE_AUTH_MODE,
    supabase_client_ready: Boolean(supabaseAuthProvider?.clientReady),
    supabase_oauth_ready: Boolean(supabaseAuthProvider?.oauthReady),
    supabase_admin_ready: Boolean(supabaseAuthProvider?.adminReady),
    supabase_url: supabaseAuthProvider?.baseUrl || null,
    supabase_email_verify_redirect: SUPABASE_EMAIL_VERIFY_REDIRECT || null,
  });
});
};

module.exports = { registerAuthResetModeRoutes };
