const buildAuthDeps = ({ core, domain }) => {
  const { configValues, providers, authSupport, requestUtils } = core;
  const { contactVerificationUtils, phoneChangeService, notificationUtils, verificationUtils, authMiddleware, sanitizeUser } = domain;

  return {
    normalizeEmail: authSupport.normalizeEmail,
    parsePhoneInput: authSupport.parsePhoneInput,
    normalizePhone: authSupport.normalizePhone,
    hashPassword: authSupport.hashPassword,
    generateTemporaryPassword: authSupport.generateTemporaryPassword,
    generateOtpCode: authSupport.generateOtpCode,
    OTP_TTL_SECONDS: configValues.OTP_TTL_SECONDS,
    OTP_MAX_ATTEMPTS: configValues.OTP_MAX_ATTEMPTS,
    notificationService: providers.notificationService,
    createNotificationEvent: notificationUtils.createNotificationEvent,
    EMAIL_DELIVERY_MODE: configValues.EMAIL_DELIVERY_MODE,
    emailVerificationProvider: providers.emailVerificationProvider,
    updateNotificationEventStatus: notificationUtils.updateNotificationEventStatus,
    AUTH_LOGIN_OTP_EXPOSE_CODE: configValues.AUTH_LOGIN_OTP_EXPOSE_CODE,
    isSupabaseEmailAuthUsable: authMiddleware.isSupabaseEmailAuthUsable,
    supabaseAuthProvider: providers.supabaseAuthProvider,
    syncLocalUserFromSupabaseAuth: authMiddleware.syncLocalUserFromSupabaseAuth,
    getSupabaseUserMetadata: authMiddleware.getSupabaseUserMetadata,
    sanitizeUser,
    generateToken: authSupport.generateToken,
    toSupabaseSessionPayload: authMiddleware.toSupabaseSessionPayload,
    verifyPassword: authSupport.verifyPassword,
    isSupabaseAuthStrictMode: authMiddleware.isSupabaseAuthStrictMode,
    queueContactVerificationRequest: contactVerificationUtils.queueContactVerificationRequest,
    getRequestIp: requestUtils.getRequestIp,
    syncLocalEmailVerifiedFromSupabase: authMiddleware.syncLocalEmailVerifiedFromSupabase,
    completeContactVerificationRequests: contactVerificationUtils.completeContactVerificationRequests,
    EMAIL_VERIFY_MAX_ATTEMPTS: configValues.EMAIL_VERIFY_MAX_ATTEMPTS,
    hashVerificationToken: authSupport.hashVerificationToken,
    getBearerTokenFromRequest: authSupport.getBearerTokenFromRequest,
    isSupabaseEmailVerified: authMiddleware.isSupabaseEmailVerified,
    EMAIL_VERIFICATION_MODE: configValues.EMAIL_VERIFICATION_MODE,
    SUPABASE_AUTH_MODE: configValues.SUPABASE_AUTH_MODE,
    WHATSAPP_DELIVERY_MODE: configValues.WHATSAPP_DELIVERY_MODE,
    whatsappProvider: providers.whatsappProvider,
    processPendingPhoneChangeRequests: phoneChangeService.processPendingPhoneChangeRequests,
    getLatestPhoneChangeRequestForUser: phoneChangeService.getLatestPhoneChangeRequestForUser,
    serializePhoneChangeRequest: phoneChangeService.serializePhoneChangeRequest,
    getOpenPhoneChangeRequestForUser: phoneChangeService.getOpenPhoneChangeRequestForUser,
    rejectPhoneChangeRequest: phoneChangeService.rejectPhoneChangeRequest,
    createAppNotification: notificationUtils.createAppNotification,
    PHONE_CHANGE_STATUS_REJECTED: configValues.PHONE_CHANGE_STATUS_REJECTED,
    PHONE_CHANGE_AUTO_BATCH_SIZE: configValues.PHONE_CHANGE_AUTO_BATCH_SIZE,
    normalizeContactVerificationRequestType: contactVerificationUtils.normalizeContactVerificationRequestType,
    AUTH_FLOW_MODE: configValues.AUTH_FLOW_MODE,
    OTP_PROVIDER: configValues.OTP_PROVIDER,
    OTP_DELIVERY_MODE: configValues.OTP_DELIVERY_MODE,
    OTP_VERIFY_SESSION_TTL_SECONDS: configValues.OTP_VERIFY_SESSION_TTL_SECONDS,
    PHONE_VERIFICATION_REQUIRED: configValues.PHONE_VERIFICATION_REQUIRED,
    WHATSAPP_PROVIDER: configValues.WHATSAPP_PROVIDER,
    SUPABASE_EMAIL_VERIFY_REDIRECT: configValues.SUPABASE_EMAIL_VERIFY_REDIRECT,
    PHONE_VERIFY_MAX_ATTEMPTS: configValues.PHONE_VERIFY_MAX_ATTEMPTS,
    hashOpaqueToken: authSupport.hashOpaqueToken,
    runCustomerRequestPurge: domain.customerRequestRetention.runCustomerRequestPurge,
    getPhoneMergeImpactSummary: phoneChangeService.getPhoneMergeImpactSummary,
    PHONE_CHANGE_STATUS_PENDING: configValues.PHONE_CHANGE_STATUS_PENDING,
    PHONE_CHANGE_STATUS_APPROVED: configValues.PHONE_CHANGE_STATUS_APPROVED,
    normalizePhoneChangeRequestStatus: phoneChangeService.normalizePhoneChangeRequestStatus,
    approvePhoneChangeRequest: phoneChangeService.approvePhoneChangeRequest,
    PHONE_CHANGE_DECISION_ADMIN: configValues.PHONE_CHANGE_DECISION_ADMIN,
    notifyPhoneChangeApproved: phoneChangeService.notifyPhoneChangeApproved,
    notifyPhoneChangeSubmitted: phoneChangeService.notifyPhoneChangeSubmitted,
    logAdminAuditAsync: core.adminAudit.logAdminAuditAsync,
    notifyPhoneChangeRejected: phoneChangeService.notifyPhoneChangeRejected,
    sendEmailVerificationChallenge: verificationUtils.sendEmailVerificationChallenge,
    markContactVerificationRequestSent: contactVerificationUtils.markContactVerificationRequestSent,
    sendPhoneVerificationChallenge: verificationUtils.sendPhoneVerificationChallenge,
    rejectContactVerificationRequest: contactVerificationUtils.rejectContactVerificationRequest,
    queuePhoneChangeRequest: phoneChangeService.queuePhoneChangeRequest,
    parseDataUrlImage: core.profileImages.parseDataUrlImage,
    PROFILE_IMAGE_ALLOWED_MIME: core.profileImages.PROFILE_IMAGE_ALLOWED_MIME,
    PROFILE_IMAGE_MAX_BYTES: core.profileImages.PROFILE_IMAGE_MAX_BYTES,
    mimeToExt: core.profileImages.mimeToExt,
    buildProfileImagePath: core.profileImages.buildProfileImagePath,
    deleteManagedProfileImage: core.profileImages.deleteManagedProfileImage,
    profileImageStorage: core.profileImages.profileImageStorage,
    PROFILE_UPLOAD_DIR: configValues.PROFILE_UPLOAD_DIR,
  };
};

module.exports = { buildAuthDeps };
