const purchase = require('../../features/purchase');

const buildPurchaseDeps = ({ core, domain }) => {
  const { configValues } = core;
  const {
    purchaseHelpers,
    purchaseTransactionUtils,
    distributorLedger,
    distributorUtils,
    supplierUtils,
    purchaseOperations,
    commerceNotifications,
    authMiddleware,
  } = domain;

  return {
    normalizeTransactionDate: purchaseHelpers.normalizeTransactionDate,
    acquirePurchaseDuplicateLockAsync: purchaseHelpers.acquirePurchaseDuplicateLockAsync,
    buildPurchaseDuplicateKey: purchaseHelpers.buildPurchaseDuplicateKey,
    buildPurchaseTransactionTimestamp: purchaseTransactionUtils.buildPurchaseTransactionTimestamp,
    calculatePoPaymentSnapshot: purchaseHelpers.calculatePoPaymentSnapshot,
    canPoAcceptPayment: purchaseHelpers.canPoAcceptPayment,
    canPoReceiveInventory: purchaseHelpers.canPoReceiveInventory,
    computeAverageDays: purchaseHelpers.computeAverageDays,
    computeAverageGapDays: purchaseHelpers.computeAverageGapDays,
    computePurchasePaymentDueDate: purchaseHelpers.computePurchasePaymentDueDate,
    computeStdDev: purchaseHelpers.computeStdDev,
    createDistributorLedgerEntry: distributorLedger.createDistributorLedgerEntry,
    createPurchaseConflictError: purchaseHelpers.createPurchaseConflictError,
    derivePoLifecycleFromPaymentStatus: purchaseHelpers.derivePoLifecycleFromPaymentStatus,
    derivePurchaseNextAction: purchaseHelpers.derivePurchaseNextAction,
    deriveStockoutRisk: purchaseHelpers.deriveStockoutRisk,
    findDuplicateDistributorBillAsync: purchaseHelpers.findDuplicateDistributorBillAsync,
    findDuplicatePurchaseOrderAsync: purchaseHelpers.findDuplicatePurchaseOrderAsync,
    findDuplicatePurchasePaymentAsync: purchaseHelpers.findDuplicatePurchasePaymentAsync,
    generatePONumber: purchase.generatePONumber,
    generateReturnNumber: purchase.generateReturnNumber,
    getAllowedPurchaseUnitsForProductRow: purchaseHelpers.getAllowedPurchaseUnitsForProductRow,
    getDistributorByIdAsync: distributorUtils.getDistributorByIdAsync,
    getSupplierByIdAsync: supplierUtils?.getSupplierByIdAsync,
    getPrimarySupplierByDistributorIdAsync: supplierUtils?.getPrimarySupplierByDistributorIdAsync,
    getPurchaseOrderLifecycleStatus: purchaseHelpers.getPurchaseOrderLifecycleStatus,
    getPurchaseProductUomProfile: purchaseHelpers.getPurchaseProductUomProfile,
    handlePurchaseOperationsSummary: purchaseOperations.handlePurchaseOperationsSummary,
    isPoEditableLifecycle: purchaseHelpers.isPoEditableLifecycle,
    isUniqueViolationError: core.constants.isUniqueViolationError,
    logStockLedgerAsync: purchaseHelpers.logStockLedgerAsync,
    normalizePoLifecycleStatus: purchaseHelpers.normalizePoLifecycleStatus,
    normalizePoPaymentStatus: purchaseHelpers.normalizePoPaymentStatus,
    normalizePurchaseOrderItems: purchaseHelpers.normalizePurchaseOrderItems,
    normalizePurchaseUomToken: purchaseHelpers.normalizePurchaseUomToken,
    notifyDistributorPurchaseOrderAsync: commerceNotifications.notifyDistributorPurchaseOrderAsync,
    recordProductCostHistoryEntryAsync: purchaseHelpers.recordProductCostHistoryEntryAsync,
    recordPurchaseOrderStatusHistoryAsync: purchaseHelpers.recordPurchaseOrderStatusHistoryAsync,
    resolveInsightDateRange: purchaseHelpers.resolveInsightDateRange,
    saveDistributorPurchaseReminderAsync: purchaseOperations.saveDistributorPurchaseReminderAsync,
    syncDistributorProductsSuppliedAsync: purchaseHelpers.syncDistributorProductsSuppliedAsync,
    toPurchaseBaseQty: purchaseHelpers.toPurchaseBaseQty,
    upsertSupplierProductsAsync: purchaseHelpers.upsertSupplierProductsAsync,
    PO_LIFECYCLE_CANCELLED: purchase.PO_LIFECYCLE_CANCELLED,
    PO_LIFECYCLE_CLOSED: purchase.PO_LIFECYCLE_CLOSED,
    PO_LIFECYCLE_CONFIRMED: purchase.PO_LIFECYCLE_CONFIRMED,
    PO_LIFECYCLE_FULLY_PAID: purchase.PO_LIFECYCLE_FULLY_PAID,
    PO_LIFECYCLE_PART_PAID: purchase.PO_LIFECYCLE_PART_PAID,
    PO_LIFECYCLE_PREPARED: purchase.PO_LIFECYCLE_PREPARED,
    PO_LIFECYCLE_REVISED: purchase.PO_LIFECYCLE_REVISED,
    PO_LIFECYCLE_SENT: purchase.PO_LIFECYCLE_SENT,
    PO_PAYMENT_PAID: purchase.PO_PAYMENT_PAID,
    PO_PAYMENT_UNPAID: purchase.PO_PAYMENT_UNPAID,
    PURCHASE_STOCK_CAP: configValues.PURCHASE_STOCK_CAP,
    getDistributorPaymentPlan: purchaseHelpers.getDistributorPaymentPlan,
    normalizeBooleanFlag: purchaseHelpers.normalizeBooleanFlag,
    getDistributorLedgerRows: distributorLedger.getDistributorLedgerRows,
    handleDistributorLedgerCreate: distributorLedger.handleDistributorLedgerCreate,
    getAuthUserFromRequest: authMiddleware?.getAuthUserFromRequest,
  };
};

module.exports = { buildPurchaseDeps };
