const registerCreditFeatureBootstrap = (deps) => {
  const {
    app,
    registerCreditFeature,
    requireAuth,
    requireAdmin,
    dbGetAsync,
    dbRunAsync,
    dbAllAsync,
    dbTxAsync,
    parsePhoneInput,
    createAppNotification,
    notifyAdmins,
    runCustomerRequestPurge,
    logAdminAuditAsync,
    normalizeCreditIssueStatus,
    getLatestCreditEntryAsync,
    buildPaymentActivityBadges,
    recalculateCreditBalancesForUser,
    normalizeTransactionDate,
    buildCreditTransactionTimestamp,
    CREDIT_ENTRY_DEDUP_WINDOW_MS,
    toTimestampMs,
    resolveClientRequestId,
    isUniqueViolationError,
    parseDataUrlImage,
    PROFILE_IMAGE_ALLOWED_MIME,
    PROFILE_IMAGE_MAX_BYTES,
    mimeToExt,
    deleteManagedProfileImage,
    profileImageStorage,
    crypto,
  } = deps;

  registerCreditFeature({
    app,
    requireAuth,
    requireAdmin,
    dbGetAsync,
    dbRunAsync,
    dbAllAsync,
    dbTxAsync,
    parsePhoneInput,
    createAppNotification,
    notifyAdmins,
    runCustomerRequestPurge,
    logAdminAuditAsync,
    normalizeCreditIssueStatus,
    getLatestCreditEntryAsync,
    buildPaymentActivityBadges,
    recalculateCreditBalancesForUser,
    normalizeTransactionDate,
    buildCreditTransactionTimestamp,
      CREDIT_ENTRY_DEDUP_WINDOW_MS,
      toTimestampMs,
      resolveClientRequestId,
      isUniqueViolationError,
      parseDataUrlImage,
      PROFILE_IMAGE_ALLOWED_MIME,
      PROFILE_IMAGE_MAX_BYTES,
      mimeToExt,
      deleteManagedProfileImage,
      profileImageStorage,
      crypto,
    });
};

module.exports = { registerCreditFeatureBootstrap };
